linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - godot
    - gosec
    - revive
    - goimports
    - whitespace
    - misspell